In [1]:
import pandas as pd

In [2]:
parks_df = pd.read_csv("Parks-Locations.csv")
libraries_df = pd.read_csv("libraries-json.csv")
housing_df = pd.read_csv("Affordable-Rental-Housing-Developments.csv")

In [12]:
parks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581 entries, 0 to 580
Data columns (total 75 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   PARK NUMBER                        581 non-null    int64
 1   PARK NAME                          581 non-null    object
 2   STREET ADDRESS                     580 non-null    object
 3   ZIP                                581 non-null    int64
 4   ACRES                              581 non-null    object
 5   WARD                               581 non-null    int64
 6   PARK CLASS                         581 non-null    object
 7   LABEL                              581 non-null    object
 8   WHEELCHAIR ACCESSIBLE BALL FIELDS  581 non-null    int64
 9   ALFRED CALDWELL LILY POND          581 non-null    int64
 10  ARCHERY RANGE                      581 non-null    int64
 11  ARTIFICIAL TURF FIELDS             581 non-null    int64
 12  BAND SHELL                         581 non-null    int64
 13  BASEBALL BATTING CAGES             581 non-null    int64
 14  BASKETBALL BACKBOARDS              581 non-null    int64
 15  BASKETBALL COURTS                  581 non-null    int64
 16  BEACH                              581 non-null    int64
 17  BOAT LAUNCH (MOTORIZED)            581 non-null    int64
 18  BOAT LAUNCH (NON-MOTORIZED)        581 non-null    int64
 19  BOAT SLIPS                         581 non-null    int64
 20  BOCCE COURT                        581 non-null    int64
 21  BOWLING GREEN                      581 non-null    int64
 22  CASTING AREA                       581 non-null    int64
 23  CHESS PAVILLION                    581 non-null    int64
 24  FOOTBALL SOCCER COMBO              581 non-null    int64
 25  COMMUNITY GARDEN                   581 non-null    int64
 26  CONSERVATORY                       581 non-null    int64
 27  CULTURAL CENTER                    581 non-null    int64
 28  DOG-FRIENDLY                       581 non-null    int64
 29  FITNESS CENTER                     581 non-null    int64
 30  FITNESS COURSES                    581 non-null    int64
 31  GALLERY                            581 non-null    int64
 32  GARDEN                             581 non-null    int64
 33  GOLF COURSE                        581 non-null    int64
 34  GOLF DRIVING RANGE                 581 non-null    int64
 35  GOLF PUTTING GREENS                581 non-null    int64
 36  GYMNASIUM                          581 non-null    int64
 37  GYMNASTIC CENTERS                  581 non-null    int64
 38  HANDBALL/RAQUETBALL COURT          581 non-null    int64
 39  HANDBALL                           581 non-null    int64
 40  HORSESHOE COURTS                   581 non-null    int64
 41  ICE SKATING                        581 non-null    int64
 42  POOL INDOOR                        581 non-null    int64
 43  BASEBALL JR/SOFTBALL/T-BALL        581 non-null    int64
 44  MOUNTAIN BIKE TRAIL                581 non-null    int64
 45  NATURE CENTER                      581 non-null    int64
 46  POOL OUTDOOR                       581 non-null    int64
 47  PAVILLION                          581 non-null    int64
 48  ZOO                                581 non-null    int64
 49  PLAYGROUND                         581 non-null    int64
 50  PLAYGROUND PARK                    581 non-null    int64
 51  ROWING CLUB                        581 non-null    int64
 52  VOLLEYBALL                         581 non-null    int64
 53  SENIOR CENTER                      581 non-null    int64
 54  SHUFFLEBOARD                       581 non-null    int64
 55  SKATE PARK                         581 non-null    int64
 56  SLED HILL                          581 non-null    int64
 57  SPORT ROLLER COURTS                581 non-null    int64
 58  SPRAY FEATURE                      581 non-null    int64
 59  BASEBALL SR                        581 non-null    int64
 60  TENNIS COURTS                      581 non-null    int64
 61  TRACK                              581 non-null    int64
 62  VOLLEYBALL SAND                    581 non-null    int64
 63  WATER PLAYGROUND                   581 non-null    int64
 64  WATER SLIDE                        581 non-null    int64
 65  BOXING CENTER                      581 non-null    int64
 66  WETLAND AREA                       581 non-null    int64
 67  LAGOON                             581 non-null    int64
 68  CAROUSEL                           581 non-null    int64
 69  CROQUET                            581 non-null    int64
 70  GOLF COURSE MINIATURE              581 non-null    int64
 71  MODEL TRAIN DISPLAY                581 non-null    int64
 72  MODEL YACHT BASIN                  581 non-null    int64
 73  CRICKET FIELD                      581 non-null    int64
 74  LOCATION                           580 non-null    object
dtypes: int64(69), object(6)
memory usage: 340.6+ KB

In [27]:
parks_agg = parks_df.groupby("ZIP").count().reset_index()
parks_agg = parks_agg[["ZIP", "PARK NAME"]]
parks_agg.rename(columns={'ZIP':'zip'}, inplace=True)
parks_agg.rename(columns={'PARK NAME':'park_count'}, inplace=True)
parks_agg.head()

     zip  park_count
0  60602           1
1  60604           1
2  60605           6
3  60606           2
4  60607           4

In [28]:
libraries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Branch                           81 non-null     object
 1   Service Hours                    81 non-null     object
 2   Address                          81 non-null     object
 3   City                             81 non-null     object
 4   State                            81 non-null     object
 5   Zip                              81 non-null     int64
 6   Branch Email                     81 non-null     object
 7   Phone Number                     80 non-null     object
 8   Website                          81 non-null     object
 9   Latitude                         81 non-null     float64
 10  Longitude                        81 non-null     float64
 11  _ - :@computed_region_rpca_8um6  81 non-null     int64
 12  _ - :@computed_region_vrxf_vc4k  81 non-null     int64
 13  _ - :@computed_region_6mkv_f3dw  81 non-null     int64
 14  _ - :@computed_region_bdys_3d7i  81 non-null     int64
 15  _ - :@computed_region_43wa_7qmu  81 non-null     int64
dtypes: float64(2), int64(6), object(8)
memory usage: 10.3+ KB

In [29]:
libraries_agg = libraries_df.groupby("Zip").count().reset_index()
libraries_agg = libraries_agg[["Zip", "Branch"]]
libraries_agg.rename(columns={'Zip':'zip'}, inplace=True)
libraries_agg.rename(columns={'Branch':'library_count'}, inplace=True)
libraries_agg.head()

     zip  library_count
0  60605              1
1  60607              2
2  60608              2
3  60609              5
4  60610              1

In [30]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Community Area Name    598 non-null    object
 1   Community Area Number  598 non-null    int64
 2   Property Type          598 non-null    object
 3   Property Name          598 non-null    object
 4   Address                598 non-null    object
 5   Zip Code               598 non-null    int64
 6   Phone Number           598 non-null    object
 7   Management Company     598 non-null    object
 8   Units                  598 non-null    int64
 9   X Coordinate           598 non-null    float64
 10  Y Coordinate           598 non-null    float64
 11  Latitude               598 non-null    float64
 12  Longitude              598 non-null    float64
 13  Location               589 non-null    object
dtypes: float64(4), int64(3), object(7)
memory usage: 65.5+ KB

In [31]:
housing_agg = housing_df.groupby("Zip Code").count().reset_index()
housing_agg = housing_agg[["Zip Code", "Community Area Name"]]
housing_agg.rename(columns={'Zip Code':'zip'}, inplace=True)
housing_agg.rename(columns={'Community Area Name':'housing_count'}, inplace=True)
housing_agg.head()

     zip  housing_count
0  60601              2
1  60605              6
2  60607             19
3  60608             38
4  60609             17

In [32]:
print(parks_agg.shape, libraries_agg.shape, housing_agg.shape)

(55, 2) (49, 2) (54, 2)

In [68]:
merge1 = pd.merge(housing_agg[['zip', 'housing_count']], libraries_agg[['zip','library_count']], how='left', left_on=['zip'], right_on=['zip'])
merge1.head()

     zip  housing_count  library_count
0  60601              2            NaN
1  60605              6            1.0
2  60607             19            2.0
3  60608             38            2.0
4  60609             17            5.0

In [63]:
merged_df = pd.merge(merge1[['zip', 'housing_count', 'library_count']], parks_agg[['zip','park_count']], how='left', left_on=['zip'], right_on=['zip'])
merged_df.head()

     zip  housing_count  library_count  park_count
0  60601              2            NaN         NaN
1  60605              6            1.0         6.0
2  60607             19            2.0         4.0
3  60608             38            2.0        21.0
4  60609             17            5.0        21.0

In [67]:
merged_df.shape

(54, 4)

In [69]:
merged_df

      zip  housing_count  library_count  park_count
0   60601              2            NaN         NaN
1   60605              6            1.0         6.0
2   60607             19            2.0         4.0
3   60608             38            2.0        21.0
4   60609             17            5.0        21.0
5   60610             16            1.0         6.0
6   60611              1            2.0         9.0
7   60612             29            2.0        14.0
8   60613             12            1.0         9.0
9   60614              5            1.0        20.0
10  60615             18            2.0        12.0
11  60616             12            2.0        17.0
12  60617              5            4.0        21.0
13  60618              7            1.0        17.0
14  60619              4            2.0        15.0
15  60620              8            2.0        16.0
16  60621             11            1.0        14.0
17  60622             24            1.0        13.0
18  60623             12            3.0        17.0
19  60624             36            1.0        15.0
20  60625              6            2.0        13.0
21  60626             10            1.0        24.0
22  60627              2            NaN         2.0
23  60628             11            2.0        13.0
24  60629              6            1.0         8.0
25  60630              3            2.0        13.0
26  60631              2            1.0        10.0
27  60632              2            3.0         7.0
28  60633              1            1.0         3.0
29  60634              4            3.0         4.0
30  60636              4            1.0         8.0
31  60637             31            1.0        15.0
32  60638              3            2.0        11.0
33  60639              7            2.0        11.0
34  60640             39            1.0        13.0
35  60641              8            1.0         7.0
36  60642              7            NaN         NaN
37  60643              2            3.0        20.0
38  60644             11            1.0        12.0
39  60645              2            1.0         8.0
40  60646              3            1.0        11.0
41  60647             56            3.0        19.0
42  60649              5            1.0         8.0
43  60651              6            1.0        10.0
44  60652              1            2.0         7.0
45  60653             45            NaN        17.0
46  60654              2            NaN         1.0
47  60657             17            2.0        10.0
48  60659              3            1.0         6.0
49  60660              8            1.0         8.0
50  60661              1            NaN         2.0
51  60707              6            1.0         NaN
52  60808              1            NaN         NaN
53  66007              1            NaN         NaN